#!/bin/bash
##############################################################################
# Blocker Detection Engine (BDE)
# Purpose: Automatically identify blocking conditions across GitHub issues
# FedRAMP: [NIST-SI-4] Information System Monitoring
# Workstream: Phase 2 - Dashboard 10X Automation (#3486)
##############################################################################

set -euo pipefail

BLOCKER_REPORT="docs/management/BLOCKER_REPORT.md"

echo "🔍 Scanning for blockers across ElevatedIQ-Mono-Repo..."

# 1. GitHub Issue Blockers
BLOCKERS=$(gh issue list --repo kushin77/ElevatedIQ-Mono-Repo --state open --label "blocked" --json number,title,labels --jq '.[] | "- [#\(.number)] \(.title)"' || echo "")

# 2. Dependency Blockers (e.g. Issue A depends on Issue B)
# We look for "Blocked by #XXX" or "Dependency: #XXX" in descriptions
DEPENDENCIES=$(gh issue list --repo kushin77/ElevatedIQ-Mono-Repo --state open --json number,title,body --jq '.[] | select(.body | contains("Blocked by #")) | "- [#\(.number)] \(.title) (Awaiting upstream dependency)"' || echo "")

# 3. Security Blockers
SECURITY_BLOCKERS=$(gh issue list --repo kushin77/ElevatedIQ-Mono-Repo --state open --label "security-blocker" --json number,title --jq '.[] | "- [#\(.number)] \(.title) (SECURITY CRITICAL)"' || echo "")

cat > "$BLOCKER_REPORT" <<EOF
# 🚨 PMO Blocker Detection Report
**Date:** $(date -u)
**Status:** $([[ -z "$BLOCKERS$DEPENDENCIES$SECURITY_BLOCKERS" ]] && echo "🟢 CLEAR" || echo "🔴 BLOCKERS DETECTED")

---

### 🛑 Active Blockers
${BLOCKERS:-"None detected."}

### ⛓️ Dependency Chains
${DEPENDENCIES:-"None detected."}

### 🛡️ Security Blockers
${SECURITY_BLOCKERS:-"None detected."}

---
*Auto-generated by Blocker Detection Engine (BDE)*
EOF

echo "✅ Blocker report generated in $BLOCKER_REPORT"

if [[ -n "$BLOCKERS$DEPENDENCIES$SECURITY_BLOCKERS" ]]; then
    echo "⚠️ ALERT: Active blockers found. Update the PMO Dashboard."
fi
