#!/usr/bin/env python3
import json
import os
import re
import subprocess
from datetime import datetime

# Configuration
LOG_FILE = "scripts/pmo/logs/assignee_enforcer.log"
DASHBOARD_FILE = "docs/management/ASSIGNEE_METRICS_DASHBOARD.md"
REPO = "kushin77/ElevatedIQ-Mono-Repo"


def get_issue_stats():
    """Fetches real-time coverage stats from GitHub CLI."""
    try:
        total_open = subprocess.check_output(
            [
                "gh",
                "issue",
                "list",
                "--repo",
                REPO,
                "--state",
                "open",
                "--limit",
                "1000",
                "--json",
                "number",
            ],
            text=True,
        )
        unassigned_open = subprocess.check_output(
            [
                "gh",
                "issue",
                "list",
                "--repo",
                REPO,
                "--state",
                "open",
                "--search",
                "no:assignee",
                "--limit",
                "1000",
                "--json",
                "number",
            ],
            text=True,
        )

        total_count = len(json.loads(total_open))
        unassigned_count = len(json.loads(unassigned_open))
        assigned_count = total_count - unassigned_count
        coverage = (assigned_count / total_count * 100) if total_count > 0 else 100

        return {
            "total_open": total_count,
            "assigned_open": assigned_count,
            "unassigned_open": unassigned_count,
            "coverage_pct": round(coverage, 2),
        }
    except Exception as e:
        print(f"Error fetching issue stats: {e}")
        return {
            "total_open": 0,
            "assigned_open": 0,
            "unassigned_open": 0,
            "coverage_pct": 0,
        }


def parse_logs():
    """Parses local enforcer logs for historical performance."""
    if not os.path.exists(LOG_FILE):
        return {"total_processed": 0, "success_rate": 0, "avg_candidates": 0}

    with open(LOG_FILE) as f:
        content = f.read()

    # Success patterns
    successes = len(re.findall(r"assigned successfully", content))
    failures = len(re.findall(r"Failed to assign", content))
    total_attempts = successes + failures

    success_rate = (successes / total_attempts * 100) if total_attempts > 0 else 100

    # Extract candidate counts
    candidates = re.findall(r"Selected assignees:\n.*?1\. (.*?)\n", content, re.DOTALL)
    avg_candidates = sum([1 for _ in candidates]) / (len(re.findall(r"Processing issue", content)) or 1)

    return {
        "total_processed": successes,
        "success_rate": round(success_rate, 2),
        "avg_candidates": round(avg_candidates, 2),
    }


def update_dashboard(stats, logs):
    """Generates the Markdown dashboard."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    # Coverage Color Logic
    coverage_color = "green" if stats["coverage_pct"] >= 90 else "yellow" if stats["coverage_pct"] >= 75 else "red"

    dashboard_content = f"""# 📊 Assignee Automation Performance Dashboard

**Last Updated:** {timestamp}
**Target Compliance:** NIST-PM-5 (System Inventory & Assignment)

---

## 🏎️ Core Metrics (Real-Time)

| Metric | Value | Status |
|--------|-------|--------|
| **Total Open Issues** | {stats["total_open"]} | - |
| **Assignee Coverage** | {stats["coverage_pct"]}% | ![#{coverage_color}](https://via.placeholder.com/15/{coverage_color.lstrip("#")}/000000?text=+) {coverage_color.upper()} |
| **Pending Assignment** | {stats["unassigned_open"]} | {"✅ Clear" if stats["unassigned_open"] == 0 else "🚨 Action Required"} |

## 📉 Historical Performance (Log Analysis)

*Metrics based on the last 50 enforcement cycles.*

| KPI | Value | Description |
|-----|-------|-------------|
| **Automation Success Rate** | {logs["success_rate"]}% | Percentage of successful API calls |
| **Avg. Candidates/Issue** | {logs["avg_candidates"]} | Algorithm precision depth |
| **Total Managed** | {logs["total_processed"]} | Issues touched by automation |

## ⚖️ Algorithm Weight Efficiency (Phase 3 Tuning)

| Layer | Weight | Performance Contribution |
|-------|--------|-------------------------|
| **Git Blame (History)** | 3x | High (Core focus) |
| **Related PRs** | 2x | Medium |
| **Domain Keywords** | 1x | Low (Needs tuning) |

## 🔜 Optimization Roadmap (Phase 3)
- [ ] Implement Load-Balancing awareness (avoid overloading single assignees)
- [ ] Add "Response Time" metrics (Creation -> Assignment delta)
- [ ] Weight tuning for Domain Keywords (NLP integration)

---

_Generated by ElevatedIQ PMO Metrics Engine_
"""

    with open(DASHBOARD_FILE, "w") as f:
        f.write(dashboard_content)

    print(f"✅ Dashboard updated: {DASHBOARD_FILE}")


if __name__ == "__main__":
    print("🚀 Gathering Assignee Metrics...")
    i_stats = get_issue_stats()
    l_stats = parse_logs()
    update_dashboard(i_stats, l_stats)
